// Generated by   : ImageConverter 565 Online
// Generated from : globe.png
// Time generated : Sun, 14 Jun 20 11:55:40 +0200  (Server timezone: CET)
// Image Size     : 8x8 pixels
// Memory usage   : 128 bytes


const uint16_t globe_white = display.color565(255, 255, 255);
const uint16_t globe_blue = display.color565(0, 50, 255);
const uint16_t globe_green = display.color565(0, 255, 50);

static const uint16_t globe[64] PROGMEM={
0x0000, 0x0000, globe_white, globe_white, globe_blue, globe_blue, 0x0000, 0x0000, 0x0000, globe_green, globe_blue, globe_green, globe_blue, globe_blue, globe_white, 0x0000,   // 0x0010 (16) pixels
globe_green, globe_green, globe_green, globe_green, globe_green, globe_blue, globe_blue, globe_white, globe_green, globe_green, globe_green, globe_green, globe_blue, globe_blue, globe_blue, globe_blue,   // 0x0020 (32) pixels
globe_blue, globe_green, globe_blue, globe_blue, globe_blue, globe_blue, globe_blue, globe_blue, globe_blue, globe_blue, globe_green, globe_blue, globe_green, globe_green, globe_green, globe_blue,   // 0x0030 (48) pixels
0x0000, globe_blue, globe_blue, globe_blue, globe_green, globe_green, globe_green, 0x0000, 0x0000, 0x0000, globe_blue, globe_blue, globe_blue, globe_green, 0x0000, 0x0000,   // 0x0040 (64) pixels
};

const uint16_t up_colour = display.color565(110, 10, 204);

static const uint16_t up[35] PROGMEM={
0x0000, 0x0000, up_colour, 0x0000, 0x0000,
0x0000, up_colour, up_colour, up_colour, 0x0000,
up_colour, 0x0000, up_colour, 0x0000, up_colour,
0x0000, 0x0000, up_colour, 0x0000, 0x0000,
0x0000, 0x0000, up_colour, 0x0000, 0x0000,
0x0000, 0x0000, up_colour, 0x0000, 0x0000,
0x0000, 0x0000, up_colour, 0x0000, 0x0000
};

const uint16_t down_colour = display.color565(250, 88, 12);

static const uint16_t down[35] PROGMEM={
0x0000, 0x0000, down_colour, 0x0000, 0x0000,
0x0000, 0x0000, down_colour, 0x0000, 0x0000,
0x0000, 0x0000, down_colour, 0x0000, 0x0000,
0x0000, 0x0000, down_colour, 0x0000, 0x0000, 
down_colour, 0x0000, down_colour, 0x0000, down_colour,
0x0000, down_colour, down_colour, down_colour, 0x0000,
0x0000, 0x0000, down_colour, 0x0000, 0x0000
};
