// Generated by   : ImageConverter 565 Online
// Generated from : globe.png
// Time generated : Sun, 14 Jun 20 11:55:40 +0200  (Server timezone: CET)
// Image Size     : 8x8 pixels
// Memory usage   : 128 bytes


const uint16_t globe_white = display.color565(255, 255, 255);
const uint16_t globe_blue = display.color565(0, 50, 255);
const uint16_t globe_green = display.color565(0, 255, 50);

static const uint16_t globe[64] PROGMEM={
0x0000, 0x0000, globe_white, globe_white, globe_blue, globe_blue, 0x0000, 0x0000, 0x0000, globe_green, globe_blue, globe_green, globe_blue, globe_blue, globe_white, 0x0000,   // 0x0010 (16) pixels
globe_green, globe_green, globe_green, globe_green, globe_green, globe_blue, globe_blue, globe_white, globe_green, globe_green, globe_green, globe_green, globe_blue, globe_blue, globe_blue, globe_blue,   // 0x0020 (32) pixels
globe_blue, globe_green, globe_blue, globe_blue, globe_blue, globe_blue, globe_blue, globe_blue, globe_blue, globe_blue, globe_green, globe_blue, globe_green, globe_green, globe_green, globe_blue,   // 0x0030 (48) pixels
0x0000, globe_blue, globe_blue, globe_blue, globe_green, globe_green, globe_green, 0x0000, 0x0000, 0x0000, globe_blue, globe_blue, globe_blue, globe_green, 0x0000, 0x0000,   // 0x0040 (64) pixels
};

const uint16_t ccolor = display.color565(247, 35, 12);

static const uint16_t client_icon[49] PROGMEM={
  ccolor, ccolor, ccolor, ccolor, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, 0x0000, ccolor, ccolor, 0x0000,
  ccolor, ccolor, ccolor, 0x0000, 0x0000, ccolor, 0x0000,
  0x0000, 0x0000, 0x0000, ccolor, 0x0000, 0x0000, ccolor,
  0x0000, 0x0000, 0x0000, 0x0000, ccolor, 0x0000, ccolor,
  ccolor, ccolor, 0x0000, 0x0000, ccolor, 0x0000, ccolor,
  ccolor, ccolor, 0x0000, 0x0000, ccolor, 0x0000, ccolor
};

const uint16_t gcolor = display.color565(247, 35, 12);

static const uint16_t guest_icon[49] PROGMEM={
  0x0000, 0x0000, 0x0000, gcolor, 0x0000, 0x0000, 0x0000,
  0x0000, 0x0000, gcolor, gcolor, gcolor, 0x0000, 0x0000,
  0x0000, 0x0000, gcolor, gcolor, gcolor, 0x0000, 0x0000,
  0x0000, 0x0000, gcolor, gcolor, gcolor, 0x0000, 0x0000,
  0x0000, 0x0000, 0x0000, gcolor, 0x0000, 0x0000, 0x0000,
  0x0000, gcolor, gcolor, gcolor, gcolor, gcolor, 0x0000,
  0x0000, gcolor, gcolor, gcolor, gcolor, gcolor, 0x0000
};

const uint16_t ucolor = display.color565(204, 20, 170);

static const uint16_t up_icon[35] PROGMEM={
  0x0000, 0x0000, ucolor, 0x0000, 0x0000,
  0x0000, ucolor, ucolor, ucolor, 0x0000,
  ucolor, 0x0000, ucolor, 0x0000, ucolor,
  0x0000, 0x0000, ucolor, 0x0000, 0x0000,
  0x0000, 0x0000, ucolor, 0x0000, 0x0000,
  0x0000, 0x0000, ucolor, 0x0000, 0x0000,
  0x0000, 0x0000, ucolor, 0x0000, 0x0000
};

const uint16_t dcolor = display.color565(250, 88, 12);

static const uint16_t down_icon[35] PROGMEM={
  0x0000, 0x0000, dcolor, 0x0000, 0x0000,
  0x0000, 0x0000, dcolor, 0x0000, 0x0000,
  0x0000, 0x0000, dcolor, 0x0000, 0x0000,
  0x0000, 0x0000, dcolor, 0x0000, 0x0000,
  dcolor, 0x0000, dcolor, 0x0000, dcolor,
  0x0000, dcolor, dcolor, dcolor, 0x0000,
  0x0000, 0x0000, dcolor, 0x0000, 0x0000
};
